version: '3.3'

networks:
  robopop:
    driver: overlay

services:
  epistemics-mysql:
    image: mysql:5.6
    networks:
      - robopop
    expose:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_SCHEMA}
    volumes:
      -
        type: volume
        source: epistemics-data
        target: /var/lib/mysql
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
  epistemics:
    image: ${DOCKER_REPOSITORY}/epistemics:${EPISTEMICS_IMAGE_VERSION}
    networks:
      - robopop
    ports:
      - target: 8080
        published: ${SERVER_PORT}
    depends_on:
      - epistemics-mysql
    volumes:
      -
        type: volume
        source: epistemics-config
        target: /usr/local/selemca
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
  silicon-coppelia:
    image: ${DOCKER_REPOSITORY}/silicon-coppelia${SICO_SUFFIX}:${SICO_IMAGE_VERSION}
    networks:
      - robopop
    ports:
      - target: 8080
        published: ${SICO_SERVER_PORT}
    environment:
      - DISPLAY=${DISPLAY}

volumes:
  epistemics-data:
  epistemics-config:
